#!/bin/bash

set -eu

log=$(mktemp)
out=$HOME/flamegraph.svg

python3 -m flamegraph -o $log build/bin/transom render input output
../FlameGraph/flamegraph.pl $log > $out

echo "RESULT: $out"

rm $log
