name: main
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: apt update
    - run: apt install python3 npm
    - run: npm install -g livereload
    - run: ./plano test
