name: main
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - uses: actions/setup-node@v3
    - run: npm install -g livereload
    - run: ./plano test
