name: main
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update -qq
    - run: sudo apt install -qq python3 npm
    - run: npm install -g livereload
    - run: ./plano test
